/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/Contact': RouteRecordInfo<'/Contact', '/Contact', Record<never, never>, Record<never, never>>,
    '/CustomTabs': RouteRecordInfo<'/CustomTabs', '/CustomTabs', Record<never, never>, Record<never, never>>,
    '/OpenSource': RouteRecordInfo<'/OpenSource', '/OpenSource', Record<never, never>, Record<never, never>>,
    '/PrivacyPolicy': RouteRecordInfo<'/PrivacyPolicy', '/PrivacyPolicy', Record<never, never>, Record<never, never>>,
    '/QA': RouteRecordInfo<'/QA', '/QA', Record<never, never>, Record<never, never>>,
    '/TermsOfService': RouteRecordInfo<'/TermsOfService', '/TermsOfService', Record<never, never>, Record<never, never>>,
  }
}
